### PR TITLE
Pin versions for next release (of assignable webview)

### PR DESCRIPTION
**Pull request by pumazi**

### CODE REVIEW

**Comment by pumazi** [comment]
Did I forget anything? cnx-db, cnx-epub, rhaptos.cnxmlutils, cnx-easybake, cnx-archive, cnx-publishing

The only other thing would be to check what versions of dependencies are installed on qa and dev that differ from those already in the requirements files.

**Comment by karenc** [comment]
[[CTE.pipeline1.16] Deploy Assignable Webview to Production](https://trello.com/c/0BVWfU3T/175-ctepipeline116-deploy-assignable-webview-to-production)

**Comment by reedstrm** [comment]
Also, the legacy side of this - should that be a separate PR?

**Comment by karenc** [comment]
Most legacy changes are probably already deployed to prod but I'll check.  See also #374

**Comment by karenc** [comment]
Production has more packages installed, but the versions of installed packages are the same between QA and Production.  So no need to do anything.

**Comment by reedstrm** [comment]
Right, except for the two new PRs I asked for review of this morning, to fix the colliding collection ids …

**Pull request merged**
