### PR TITLE
Create pdf_gen_common role for zclient and pdf_gen

### LINKED ISSUE #353: PDF generation by download fails on legacy staging
## Summary

It should be possible to trigger PDF generation by clicking the download link on the zope site.  On staging, it is returning "PDFLatexError":

```
2017-08-02T12:29:39 ERROR Zope.SiteErrorLog http://legacy-staging.cnx.org/content/m10864/2.3/index_html
Traceback (innermost last):
  Module ZPublisher.Publish, line 115, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 41, in call_object
  Module Products.RhaptosModuleStorage.ModuleView, line 156, in index_html
  Module Products.RhaptosModuleStorage.ModuleView, line 484, in default
  Module Products.RhaptosModuleStorage.ModuleView, line 629, in downloadPDF
  Module Products.RhaptosPDFLatexTool.PDFLatexTool, line 142, in convertFSDirToPDF
PDFLatexError: No output file
```

Looking at PDFLatexTool, I think it is trying to generate the PDF file without enqueuing it.  There are packages that are only installed on the pdf_gen servers, not on the zclient servers.  This is probably the reason why we are seeing this failure.

## Environment

staging (affects all environments where zclients and pdf_gen are on different servers)

### PR DESCRIPTION
**Pull request by karenc**
On the legacy site, PDFs are generated if they are not on the filesystem
when a user clicks on the download link, so zclients need to be able to
generate PDFs.

Create the pdf_gen_common role that both zclient and pdf_gen depend on
so that they both get all the packages and fonts necessary.

Close #353 

---

This has already been deployed to staging as [v2.1.3](https://github.com/Connexions/cnx-deploy/commits/v2.1.3).  Just need to add this to master.

### CODE REVIEW

**Comment by pumazi** [comment]
😆  That's not exactly what I meant. I was asking that we completely move the contents of this new pdf_gen_common to zope_common. 😛

**Comment by karenc** [comment]
Wait, I forgot to remove the role. :stuck_out_tongue:

**Comment by karenc** [comment]
I've moved pdf_gen_common/tasks/main.yml to zope_common/tasks/pdf_gen_dependencies.yml, is that good?

**Comment by karenc** [comment]
I'm not sure where files should go but this is what I have locally (one that has zope set up before this url becomes 404):

```
karen@xenial-openstax:/var/cnx/venvs/publishing/src/cnx-archive$ find /var/lib/cnx/cnx-buildout -name 'egenix*'
/var/lib/cnx/cnx-buildout/downloads/egenix-mx-base-3.2.5.tar.gz
/var/lib/cnx/cnx-buildout/downloads/dist/egenix_mx_base-3.2.5-py2.4-linux-x86_64.egg
/var/lib/cnx/cnx-buildout/parts/egenix-source
/var/lib/cnx/cnx-buildout/parts/egenix-source/egenix_mx_base.py
/var/lib/cnx/cnx-buildout/eggs/egenix_mx_base-3.2.5-py2.4-linux-x86_64.egg
```

**Comment by pumazi** [comment]
@DarkPrinceFrost This is ready for you to look over and merge.

**Pull request merged**
