### PR TITLE
switch on stub accounts for all environments

### PR DESCRIPTION
**Pull request by reedstrm**
There is currently no need for publishing to talk to accounts. Turn on stub accounts instead.

### CODE REVIEW

**Comment by scb6** [comment]
The code looks OK to me, but I do not know much about what these change will do to the code base. (i.e. Mulich's comments)

**Comment by reedstrm** [comment]
Agreed - I did the minimum to deploy, but spread it across all the environments. I think perhaps the right fix for _today_ (code freeze) may be to strip this off the production environs - @pumazi is correct, we should vault the credentials. Who knows how to do that, @scb6? @DarkPrinceFrost ?

**Comment by pumazi** [comment]
Oi, lots of environments... I'm going to create a ./group_vars/vault.yml to hit all the environments. Let me know if that's an issue for you guys.

**Comment by scb6** [comment]
Looks good to me.

**Pull request merged**
