### PR TITLE
Add openstaxcms to settings.js

### PR DESCRIPTION
**Pull request by Dantemss**
I guessed the desired CMS urls based on the other urls in each config.
NOTE: several URLs in the `des` environment do not exist

Goes with https://github.com/Connexions/webview/pull/1713

### CODE REVIEW

**Comment by dtwilliamson** [comment]
I don't think the des environment is used any longer.

**Comment by reedstrm** [comment]
BTW, for all the other `-qa` settings in those files, we need to talk to @openstaxalina first, before changing anything.

**Comment by Dantemss** [comment]
@reedstrm content, devb and katalyst envs changed to prod exercises and cms

**Comment by reedstrm** [comment]
Ignoring the pyup security complaint - this PR doe not bring in that dependecy.

**Pull request merged**
